# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='the price of ltc')),
                ('timestamp', models.IntegerField(verbose_name='date of record')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
